import type { DailyBlock, Project, Task, Milestone } from "@/lib/types";

type SeedTask = Omit<
  Task,
  "userId" | "createdAt" | "updatedAt" | "source" | "projectId"
>;
type SeedMilestone = Omit<
  Milestone,
  "userId" | "createdAt" | "updatedAt" | "source" | "projectId"
>;
type SeedProject = Omit<
  Project,
  "userId" | "createdAt" | "updatedAt" | "source" | "tasks" | "milestones"
> & { tasks: SeedTask[]; milestones: SeedMilestone[] };

export const PORTFOLIO_VERSION = "2026-09-23-v1";

const projectSeeds: SeedProject[] = [
  {
    id: "pequenos-escritores",
    name: "Pequeños Escritores",
    area: "Software · Cliente",
    description:
      "App educativa infantil con retos por niveles, trazos, sonido, grupos, perfiles y progreso persistente.",
    progress: 72,
    status: "active",
    priority: "critical",
    deadline: "ACTIVO",
    accent: "#7c3aed",
    nextAction: "Reorganizar retos por categorías, desbloqueo progresivo y audio al completar trazos",
    hours: 31.8,
    stage: "execution",
    milestones: [
      { id: "p1", title: "Core y autenticación", weight: 25, progress: 92 },
      { id: "p2", title: "Retos y progresión", weight: 35, progress: 72 },
      { id: "p3", title: "Experiencia infantil", weight: 20, progress: 68 },
      { id: "p4", title: "Pulido y entrega", weight: 20, progress: 42 },
    ],
    tasks: [
      {
        id: "pt1",
        title: "Categorizar retos y desbloquear de dos en dos",
        completed: false,
        estimatedMinutes: 90,
        priority: "critical",
        milestone: "Retos y progresión",
      },
      {
        id: "pt2",
        title: "Reproducir sonido de letra o número al completar",
        completed: false,
        estimatedMinutes: 60,
        priority: "high",
        milestone: "Experiencia infantil",
      },
      {
        id: "pt3",
        title: "Mejorar profundidad visual del fondo",
        completed: false,
        estimatedMinutes: 45,
        priority: "medium",
        milestone: "Pulido y entrega",
      },
    ],
  },
  {
    id: "tesis-civil",
    name: "Tesis Ingeniería Civil",
    area: "Académico · UNI",
    description:
      "Estudio de seguridad vial de 4 km, km 284–288, tramo El Jícaro–Jalapa, comunidad El Carrizal.",
    progress: 86,
    status: "active",
    priority: "critical",
    deadline: "PREDEFENSA",
    accent: "#a78bfa",
    nextAction: "Preparar correcciones del primer documento entregado y material de predefensa",
    hours: 46.2,
    stage: "delivery",
    milestones: [
      { id: "t1", title: "Protocolo", weight: 15, progress: 100 },
      { id: "t2", title: "Desarrollo documental", weight: 35, progress: 100 },
      { id: "t3", title: "Primer documento de predefensa", weight: 20, progress: 100 },
      { id: "t4", title: "Correcciones y predefensa", weight: 20, progress: 55 },
      { id: "t5", title: "Defensa final", weight: 10, progress: 0 },
    ],
    tasks: [
      {
        id: "tt1",
        title: "Procesar observaciones del primer documento",
        completed: false,
        estimatedMinutes: 90,
        priority: "critical",
        milestone: "Correcciones y predefensa",
      },
      {
        id: "tt2",
        title: "Preparar presentación de predefensa",
        completed: false,
        estimatedMinutes: 120,
        priority: "high",
        milestone: "Correcciones y predefensa",
      },
    ],
  },
  {
    id: "dolce",
    name: "Tesis Mercadeo · DOLCE",
    area: "Académico · UNAN",
    description:
      "Análisis del marketing en el posicionamiento comercial de Repostería DOLCE en Matagalpa, primer semestre 2026.",
    progress: 84,
    status: "active",
    priority: "high",
    deadline: "CIERRE 2026",
    accent: "#c084fc",
    nextAction: "Continuar depuración del documento, resultados y presentación final",
    hours: 27.6,
    stage: "delivery",
    milestones: [
      { id: "d1", title: "Marco y antecedentes", weight: 25, progress: 100 },
      { id: "d2", title: "Metodología", weight: 20, progress: 100 },
      { id: "d3", title: "Análisis y resultados", weight: 30, progress: 82 },
      { id: "d4", title: "Documento y presentación final", weight: 25, progress: 58 },
    ],
    tasks: [
      {
        id: "dt1",
        title: "Cerrar análisis y conclusiones",
        completed: false,
        estimatedMinutes: 75,
        priority: "high",
        milestone: "Análisis y resultados",
      },
      {
        id: "dt2",
        title: "Actualizar presentación de defensa",
        completed: false,
        estimatedMinutes: 60,
        priority: "medium",
        milestone: "Documento y presentación final",
      },
    ],
  },
  {
    id: "nexus",
    name: "NEXUS",
    area: "Software · Personal",
    description:
      "Sistema personal de inteligencia, proyectos, conocimiento, finanzas, calendario, memoria e integraciones.",
    progress: 58,
    status: "active",
    priority: "critical",
    deadline: "CONTINUO",
    accent: "#d946ef",
    nextAction: "Consolidar datos reales e iniciar integraciones de Calendar, Drive y capa de IA",
    hours: 0,
    stage: "execution",
    milestones: [
      { id: "nx1", title: "Sistema visual y navegación", weight: 25, progress: 92 },
      { id: "nx2", title: "Firebase y persistencia", weight: 25, progress: 88 },
      { id: "nx3", title: "Datos y automatización", weight: 25, progress: 45 },
      { id: "nx4", title: "IA e integraciones", weight: 25, progress: 8 },
    ],
    tasks: [
      {
        id: "nxt1",
        title: "Sincronizar portafolio real",
        completed: true,
        completedAt: Date.UTC(2026, 8, 23, 12),
        estimatedMinutes: 45,
        priority: "high",
        milestone: "Datos y automatización",
      },
      {
        id: "nxt2",
        title: "Conectar Google Calendar y Drive",
        completed: false,
        estimatedMinutes: 120,
        priority: "high",
        milestone: "IA e integraciones",
      },
    ],
  },
  {
    id: "xarcon-creative",
    name: "XARCON Creative",
    area: "Empresa · Agencia",
    description:
      "Marca, portafolio, web y estructura comercial de la futura agencia de marketing y desarrollo.",
    progress: 68,
    status: "active",
    priority: "high",
    deadline: "LANZAMIENTO 2027",
    accent: "#9333ea",
    nextAction: "Convertir proyectos terminados en casos de estudio y fortalecer oferta comercial",
    hours: 22.1,
    stage: "execution",
    milestones: [
      { id: "x1", title: "Marca", weight: 20, progress: 90 },
      { id: "x2", title: "Web", weight: 30, progress: 88 },
      { id: "x3", title: "Portafolio", weight: 25, progress: 68 },
      { id: "x4", title: "Sistema comercial", weight: 25, progress: 28 },
    ],
    tasks: [
      {
        id: "xt1",
        title: "Documentar casos de estudio principales",
        completed: false,
        estimatedMinutes: 90,
        priority: "high",
        milestone: "Portafolio",
      },
    ],
  },
  {
    id: "amy-blandon",
    name: "Amy Blandón",
    area: "Software · Cliente",
    client: "Amy Blandón",
    description:
      "Web y sistema profesional para bienes raíces, seguros e inversiones, con identidad premium y herramientas comerciales.",
    progress: 92,
    status: "waiting",
    priority: "high",
    deadline: "EN REVISIÓN",
    accent: "#f59e0b",
    nextAction: "Aplicar últimos cambios cuando el cliente retome la revisión",
    hours: 0,
    stage: "delivery",
    milestones: [
      { id: "ab1", title: "Identidad y UI", weight: 30, progress: 100 },
      { id: "ab2", title: "Web comercial", weight: 35, progress: 96 },
      { id: "ab3", title: "Funciones y contenido", weight: 25, progress: 90 },
      { id: "ab4", title: "Cierre", weight: 10, progress: 45 },
    ],
    tasks: [
      {
        id: "abt1",
        title: "Esperar revisión final del cliente",
        completed: false,
        estimatedMinutes: 20,
        priority: "medium",
        milestone: "Cierre",
      },
    ],
  },
  {
    id: "drg-web",
    name: "Diamantes Realty Group · Sistema Web",
    area: "Software · Cliente",
    client: "Diamantes Realty Group",
    description:
      "Ecosistema inmobiliario con propiedades, mapa, agentes, administración, interacción y gestión de contenido.",
    progress: 88,
    status: "waiting",
    priority: "high",
    deadline: "MANTENIMIENTO",
    accent: "#1d4ed8",
    nextAction: "Retomar optimizaciones pendientes de paneles, mapa y rendimiento cuando corresponda",
    hours: 0,
    stage: "delivery",
    milestones: [
      { id: "drg1", title: "Web pública", weight: 30, progress: 96 },
      { id: "drg2", title: "Paneles y autenticación", weight: 30, progress: 88 },
      { id: "drg3", title: "Mapa y propiedades", weight: 25, progress: 90 },
      { id: "drg4", title: "Optimización", weight: 15, progress: 55 },
    ],
    tasks: [
      {
        id: "drgt1",
        title: "Revisar incidencias pendientes de panel y mapa",
        completed: false,
        estimatedMinutes: 90,
        priority: "medium",
        milestone: "Optimización",
      },
    ],
  },
  {
    id: "avaluos-drg",
    name: "Plataforma de Avalúos DRG",
    area: "Software · Ingeniería",
    client: "Diamantes Realty Group",
    description:
      "Herramienta de avalúos de casas y terrenos para Matagalpa y Estelí con cálculo, historial y PDF.",
    progress: 82,
    status: "waiting",
    priority: "medium",
    deadline: "MANTENIMIENTO",
    accent: "#2563eb",
    nextAction: "Ajustar eliminación de registros y continuar afinando el modelo de valoración",
    hours: 0,
    stage: "execution",
    milestones: [
      { id: "av1", title: "Motor de cálculo", weight: 35, progress: 88 },
      { id: "av2", title: "Persistencia e historial", weight: 25, progress: 90 },
      { id: "av3", title: "PDF premium", weight: 25, progress: 100 },
      { id: "av4", title: "Calibración y administración", weight: 15, progress: 45 },
    ],
    tasks: [
      {
        id: "avt1",
        title: "Implementar eliminación segura de avalúos",
        completed: false,
        estimatedMinutes: 45,
        priority: "medium",
        milestone: "Calibración y administración",
      },
    ],
  },
  {
    id: "web-norvin",
    name: "Web Personal · Norvin García",
    area: "Marca personal · Software",
    description:
      "Sitio profesional inmobiliario con propiedades, mapa, captación, contacto y posicionamiento personal.",
    progress: 90,
    status: "waiting",
    priority: "medium",
    deadline: "MEJORAS",
    accent: "#0f766e",
    nextAction: "Mantener contenido actualizado y ejecutar mejoras de conversión cuando sean necesarias",
    hours: 0,
    stage: "delivery",
    milestones: [
      { id: "wn1", title: "Marca y diseño", weight: 30, progress: 100 },
      { id: "wn2", title: "Propiedades y mapa", weight: 35, progress: 92 },
      { id: "wn3", title: "Captación y conversión", weight: 20, progress: 82 },
      { id: "wn4", title: "Optimización continua", weight: 15, progress: 65 },
    ],
    tasks: [
      {
        id: "wnt1",
        title: "Actualizar portafolio inmobiliario",
        completed: false,
        estimatedMinutes: 45,
        priority: "low",
        milestone: "Optimización continua",
      },
    ],
  },
  {
    id: "criscasa",
    name: "CRISCASA · Etapa 1",
    area: "Cliente · Ingeniería",
    client: "Luis Alfredo Castillo",
    description:
      "Primera etapa del proyecto CRISCASA: propuesta arquitectónica, renders, fachada y planos técnicos entregados.",
    progress: 100,
    status: "completed",
    priority: "medium",
    deadline: "ENTREGADO",
    value: 800,
    paid: 400,
    accent: "#8b5cf6",
    nextAction: "Etapa 1 cerrada; esperar una nueva fase o solicitud del cliente",
    hours: 18.4,
    stage: "delivery",
    milestones: [
      { id: "c1", title: "Diseño base", weight: 20, progress: 100 },
      { id: "c2", title: "Fachada y renders", weight: 30, progress: 100 },
      { id: "c3", title: "Planos técnicos", weight: 30, progress: 100 },
      { id: "c4", title: "Entrega etapa 1", weight: 20, progress: 100 },
    ],
    tasks: [
      {
        id: "ct1",
        title: "Completar renders de etapa 1",
        completed: true,
        completedAt: Date.UTC(2026, 8, 23, 12),
        estimatedMinutes: 90,
        priority: "high",
        milestone: "Fachada y renders",
      },
      {
        id: "ct2",
        title: "Completar planos de etapa 1",
        completed: true,
        completedAt: Date.UTC(2026, 8, 23, 12),
        estimatedMinutes: 90,
        priority: "high",
        milestone: "Planos técnicos",
      },
      {
        id: "ct3",
        title: "Entregar etapa 1",
        completed: true,
        completedAt: Date.UTC(2026, 8, 23, 12),
        estimatedMinutes: 30,
        priority: "medium",
        milestone: "Entrega etapa 1",
      },
    ],
  },
  {
    id: "casa-propia",
    name: "Casa Propia · Planos",
    area: "Personal · Ingeniería",
    description:
      "Diseño y ajuste del plano arquitectónico y eléctrico de la vivienda de 5.00 × 13.50 m.",
    progress: 78,
    status: "waiting",
    priority: "medium",
    deadline: "SIN FECHA",
    accent: "#14b8a6",
    nextAction: "Retomar detalles finales y consolidar láminas definitivas cuando se reactive",
    hours: 0,
    stage: "execution",
    milestones: [
      { id: "cp1", title: "Distribución arquitectónica", weight: 45, progress: 92 },
      { id: "cp2", title: "Plano eléctrico", weight: 35, progress: 82 },
      { id: "cp3", title: "Láminas finales", weight: 20, progress: 38 },
    ],
    tasks: [
      {
        id: "cpt1",
        title: "Consolidar versión final de planos",
        completed: false,
        estimatedMinutes: 60,
        priority: "medium",
        milestone: "Láminas finales",
      },
    ],
  },
  {
    id: "nicasa",
    name: "NICASA",
    area: "Software · Inmobiliario",
    description:
      "Mapa público de propiedades con autenticación Google y flujo de publicación inmobiliaria.",
    progress: 34,
    status: "backlog",
    priority: "low",
    deadline: "PAUSADO",
    accent: "#6d28d9",
    nextAction: "Resolver creación de documentos en Firestore antes de reactivar el proyecto",
    hours: 14.8,
    stage: "planning",
    milestones: [
      { id: "n1", title: "Interfaz y mapa", weight: 45, progress: 62 },
      { id: "n2", title: "Autenticación", weight: 20, progress: 65 },
      { id: "n3", title: "Publicación y datos", weight: 35, progress: 0 },
    ],
    tasks: [
      {
        id: "nt1",
        title: "Corregir publicación en Firestore",
        completed: false,
        estimatedMinutes: 90,
        priority: "medium",
        milestone: "Publicación y datos",
      },
    ],
  },
  {
    id: "xarcon-realty",
    name: "XARCON Realty",
    area: "Empresa · Inmobiliario",
    description:
      "Rama inmobiliaria de XARCON, reservada para el lanzamiento formal cuando opere de manera independiente.",
    progress: 28,
    status: "backlog",
    priority: "low",
    deadline: "2027",
    accent: "#b45309",
    nextAction: "Mantenerla en pausa mientras la operación inmobiliaria continúe dentro de DRG",
    hours: 0,
    stage: "planning",
    milestones: [
      { id: "xr1", title: "Concepto y marca", weight: 35, progress: 68 },
      { id: "xr2", title: "Base digital", weight: 30, progress: 42 },
      { id: "xr3", title: "Operación independiente", weight: 35, progress: 0 },
    ],
    tasks: [
      {
        id: "xrt1",
        title: "Definir relanzamiento para operación independiente",
        completed: false,
        estimatedMinutes: 60,
        priority: "low",
        milestone: "Operación independiente",
      },
    ],
  },
  {
    id: "xarcon-construcciones",
    name: "XARCON Construcciones",
    area: "Empresa · Construcción",
    description:
      "Rama de construcción y arquitectura de XARCON, orientada a coordinación de obras, diseño y servicios técnicos.",
    progress: 24,
    status: "backlog",
    priority: "low",
    deadline: "2027",
    accent: "#64748b",
    nextAction: "Definir servicios, estructura operativa y portafolio técnico antes del lanzamiento",
    hours: 0,
    stage: "planning",
    milestones: [
      { id: "xc1", title: "Concepto", weight: 30, progress: 65 },
      { id: "xc2", title: "Oferta de servicios", weight: 35, progress: 25 },
      { id: "xc3", title: "Operación", weight: 35, progress: 0 },
    ],
    tasks: [
      {
        id: "xct1",
        title: "Estructurar catálogo de servicios",
        completed: false,
        estimatedMinutes: 75,
        priority: "low",
        milestone: "Oferta de servicios",
      },
    ],
  },
  {
    id: "recoleccion-uni",
    name: "Web de Recolección de Datos · UNI",
    area: "Software · Académico",
    description:
      "Herramienta web desarrollada para apoyar la recolección de datos de un proyecto universitario.",
    progress: 100,
    status: "completed",
    priority: "low",
    deadline: "ENTREGADO",
    accent: "#0284c7",
    nextAction: "Proyecto cerrado; conservar como caso de estudio",
    hours: 0,
    stage: "delivery",
    milestones: [
      { id: "ru1", title: "Desarrollo", weight: 70, progress: 100 },
      { id: "ru2", title: "Entrega", weight: 30, progress: 100 },
    ],
    tasks: [
      {
        id: "rut1",
        title: "Entrega final",
        completed: true,
        completedAt: Date.UTC(2026, 8, 23, 12),
        estimatedMinutes: 30,
        priority: "low",
        milestone: "Entrega",
      },
    ],
  },
  {
    id: "rally-germina",
    name: "Web Rally · Germina",
    area: "Software · Académico",
    description:
      "Proyecto web desarrollado para el rally de Germina como experiencia universitaria y de portafolio.",
    progress: 100,
    status: "completed",
    priority: "low",
    deadline: "ENTREGADO",
    accent: "#16a34a",
    nextAction: "Proyecto cerrado; conservar como caso de estudio",
    hours: 0,
    stage: "delivery",
    milestones: [
      { id: "rg1", title: "Desarrollo", weight: 70, progress: 100 },
      { id: "rg2", title: "Entrega", weight: 30, progress: 100 },
    ],
    tasks: [
      {
        id: "rgt1",
        title: "Entrega final",
        completed: true,
        completedAt: Date.UTC(2026, 8, 23, 12),
        estimatedMinutes: 30,
        priority: "low",
        milestone: "Entrega",
      },
    ],
  },
];

export const todayBlocks: DailyBlock[] = [
  {
    time: "12:30",
    end: "14:00",
    projectId: "pequenos-escritores",
    title: "Retos, niveles y audio",
    type: "focus",
  },
  {
    time: "14:30",
    end: "15:30",
    projectId: "tesis-civil",
    title: "Preparación de predefensa",
    type: "focus",
  },
  {
    time: "16:00",
    end: "17:30",
    projectId: "nexus",
    title: "NEXUS · datos e integraciones",
    type: "focus",
  },
  {
    time: "18:00",
    end: "18:30",
    projectId: "xarcon-creative",
    title: "Portafolio y casos de estudio",
    type: "admin",
  },
];

const stamp = {
  userId: "local-norvin",
  createdAt: Date.UTC(2026, 8, 23, 12),
  updatedAt: Date.UTC(2026, 8, 23, 12),
  source: "demo" as const,
};

export const initialProjects: Project[] = projectSeeds.map((p) => ({
  ...p,
  ...stamp,
  metadata: {
    ...p.metadata,
    portfolioVersion: PORTFOLIO_VERSION,
  },
  tasks: p.tasks.map((t) => ({ ...t, ...stamp, projectId: p.id })),
  milestones: p.milestones.map((m) => ({ ...m, ...stamp, projectId: p.id })),
}));
